Generate git version and include that in source output
The current GIT_VERSION value only works if you build from a git
repo.  Once we release on github, the tarballs that one can download
are not git repos and the git command to describe the version fail.

Generate the git version value and write to a file.  In source tarball
builds, the value will come from the file rather than git.

- Add 'show-version' as makefile target
- Add 'show-version' to github workflow
- Adjust make-tarball tool to insert the git-version file

Signed-off-by: Ryan Harper <rharper@woxford.com>

diff --git a/tools/make-tarball b/tools/make-tarball
--- a/tools/make-tarball
+++ b/tools/make-tarball
@@ -51,7 +51,7 @@ fi
 version=${version#v}
 archive_base="stubby-$version"
 if [ -z "$output" ]; then
-    output="$archive_base.tar.gz"
+    output="$archive_base.tar"
 fi
 
 # when building an archiving from HEAD, ensure that there aren't any
@@ -66,6 +66,15 @@ if [ "$rev" = HEAD ] && ! git diff-index --quiet HEAD --; then
     fi
 fi
 
-git archive --format=tgz "--output=$output" "--prefix=$archive_base/" "$rev" ||
+# generate tar format to enable version insertion
+git archive --format=tar "--output=$output" "--prefix=$archive_base/" "$rev" ||
     fail "git archive failed"
-echo "$output"
+
+# insert the git-version value
+echo "$version" > git-version
+tar --append -f ${output} --transform "s,^,$archive_base/," git-version ||
+    fail "appending git-version to archive failed"
+gzip ${output} ||
+    fail "failed to compress archive"
+
+echo "${output}.gz"
